### PR TITLE
Fix empty query

### LINKED ISSUE #1116: Defining a Space to not require a query still requires a query.
Setting `require_query: false` on a space should allow a search with no query criteria. It appears to be ignored and still requires a query to be provided or you receive the following error from the search endpoint.

```
{"error":"Query restricted"}
```

### PR DESCRIPTION
**Pull request by peterdemartini**
Fix xlucene's translation of an empty query. I also change the code so we use the empty query over a * query.

Fixes #1116

### CODE REVIEW

**Comment by kstaken** [comment]
I'm still not getting any results when I hit a search endpoint where the query is supposed to be optional.

**Comment by kstaken** [comment]
This is showing out of date.

**Comment by kstaken** [comment]
Is this able to merge or are you still trying to fix the tests?

**Comment by peterdemartini** [comment]
Still trying to fix the tests. The e2e test are being problematic.

**Pull request merged**
