### PR TITLE
v0.36.2 improved test consistency, automation and fixed several small issues

### LINKED ISSUE #711: Support package.json start script and bin
Teraslice should support node package conventions. I suggest we add the run `npm start`, which means adding something like `"start": "node service.js"`. Additionally, the `package.json` should also have `"bin": "./service.js"` so you can install teraslice globally by running `npm install -g teraslice`.

### LINKED ISSUE #724: Automate Code Coverage
This project should report its code coverage to CodeCov, or something similar.

### PR DESCRIPTION
**Pull request by peterdemartini**
Improved test consistency in the worker and messaging unit tests. I fixed a potential double subscribing issue when I was trying to debug an event emitter leak in messaging service.

I also added CodeCoverage reporting to CodeCov (Resolves #724), updated the Dockerfile and added an npm start script (Resolves #711)

### CODE REVIEW

**Comment by peterdemartini** [comment]
I wouldn't say the integration tests are in a good place. I don't recommend merging this pull-request yet

**Comment by peterdemartini** [comment]
This should be ready to review now @kstaken

**Comment by peterdemartini** [comment]
I found some issues after merging in the changes. I need to work through them before we merge it.

**Comment by peterdemartini** [comment]
When this is merged into master, we should squash it into one commit

**Comment by jsnoble** [comment]
unit and integration tests pass

**Pull request merged**
