### PR TITLE
Data access permissions

### PR DESCRIPTION
**Pull request by peterdemartini**
Add data-access management access control / permissions, see the updated [docs](https://github.com/terascope/teraslice/blob/data-access-permissions/docs/packages/data-access-plugin/overview.md) for a list the user's permissions.

Resolves: #1049

### CODE REVIEW

**Comment by peterdemartini** [comment]
I am going to remove WIP from this PR since we should be able to move on and test the changes for now. I deferred the following changes to another PR:

- a user should only be able to see things his role has access to
- ensure client ids match when associating records
- improve graphql usage and api

**Comment by kstaken** [comment]
Is there a script to bootstrap access for the first time? It looks like the records I created previously are broken due to client_id but you now need a token to make any request so if I reset not sure how to get started again.

I noticed in the docs it says for USER: "List the users for its client, it cannot see the api_token on any user except itself." A USER shouldn't be able to see anything about other users.

**Comment by peterdemartini** [comment]
> Is there a script to bootstrap access for the first time? It looks like the records I created previously are broken due to client_id but you now need a token to make any request so if I reset not sure how to get started again.

I realize the authentication is broken when loading the playground. Also creating a script is really not ideal, because it needs to be ran from within teraserver for the connector and plugin configuration. Instead I changed the way the bootstrap mode works:

```yaml
# Enabling this flag will cause a `SUPERADMIN` user to be created when this plugin is initialized and there are no other users. The `SUPERADMIN`'s credentials are (username: admin, password: admin). Make sure to only run one worker when using this mode.
bootstrap_mode: true
```

> I noticed in the docs it says for USER: "List the users for its client, it cannot see the api_token on any user except itself." A USER shouldn't be able to see anything about other users.

I can make that change, however should the "user" be able to see something about the other users, maybe just the `firstname`?

**Comment by peterdemartini** [comment]
I am going to merge without the ci checks since travis isn't building

**Pull request merged**
