### PR TITLE
Updating the assets API setup based on foundation API changes. 

### PR DESCRIPTION
**Pull request by kstaken**
Requires terascope/terafoundation#93 to be merged

### CODE REVIEW

**Comment by kstaken** [comment]
refs #542

**Comment by godber** [comment]
The integration tests fail on this branch when trying to generate the test data:

```
Jasmine started
 - Bringing Docker environment up
 - Waiting for Elasticsearch................ Ready
 - Waiting for Teraslice......... Ready
 - Cleaning up teraslice state & prior test results
 - Making sure example data generated
    - defining index: example-logs-10 , reason: index_not_found
    - defining index: example-logs-1000 , reason: index_not_found
    - defining index: example-logs-10000-hex , reason: index_not_found
    - defining index: example-logs-10000 , reason: index_not_found
Data generation failed:  Job has status: "failed" which is terminal so status: "completed" is not possible. job_id: 728e85af-ada1-4ac6-b543-a8a3d5fb01bb
make: *** [test] Error 4
```

Perhaps my dependencies are not getting updated properly and I have the wrong version of terafoundation (not 0.2.0).

**Comment by godber** [comment]
The tests DO pass on the master branch.

**Comment by kstaken** [comment]
Check the logs. I suspect it doesn't have the new terafoundation. The tests passed for me before and I'm running them again now and they're working.

**Comment by godber** [comment]
Yeah, after nuking my `node_modules/` it get's passed that step now.

**Comment by godber** [comment]
The integration tests pass.

screen shot 2017-09-18 at 2 02 20 pm

**Pull request merged**
