### PR TITLE
fixed test, node 8 passes integration tests resolves #645

### LINKED ISSUE #645: upgrade node version
We are currently using node 4 which will not receive any more updates after this April. I recommend that we switch to node 8 as it is in active LTS mode.

- https://github.com/nodejs/Release

- http://node.green/

### PR DESCRIPTION
**Pull request by jsnoble**
Unit and integration tests pass.

### CODE REVIEW

**Comment by jsnoble** [comment]
this will need terafoundation pr to be merged

**Comment by kstaken** [comment]
Was eslint run across the source tree or something? There are a lot of code changes here especially related to destructuring. Was this necessary to actually make this work on node 8? 

This has the problem of making it backwards incompatible with node 4 and it forces us to update everything all at once which may be impossible to actually achieve. Can node 8 compatibility be achieved without breaking it on node:4?

**Comment by kstaken** [comment]
Starting with a freshly checked out source tree and running on node:8 the assets integration tests fail.

```
      ✗ After starting a job with a Type 1 asset specified by ID should eventually have all workers joined (2 secs)
        - Failed: Job submission failed, error: could not parse assets for their id's, error: Error: TypeError: Cannot read property 'length' of null
            at _getAssetId (/app/source/lib/cluster/storage/assets.js:90:28)
            at bound (domain.js:287:14)
            at runBound (domain.js:300:12)
            at tryCatcher (/app/source/node_modules/bluebird/js/main/util.js:26:23)
            at MappingPromiseArray._promiseFulfilled (/app/source/node_modules/bluebird/js/main/map.js:56:38)
            at MappingPromiseArray.init (/app/source/node_modules/bluebird/js/main/promise_array.js:92:18)
            at MappingPromiseArray.init (/app/source/node_modules/bluebird/js/main/map.js:29:23)
            at Async._drainQueue (/app/source/node_modules/bluebird/js/main/async.js:128:12)
            at Async._drainQueues (/app/source/node_modules/bluebird/js/main/async.js:133:10)
            at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/main/async.js:15:14)
            at processImmediate [as _immediateCallback] (timers.js:396:17) occurred on node: cluster_master
      ✗ After starting a job with a Type 2 asset specified by ID should eventually have all workers joined (2 secs)
        - Failed: Job submission failed, error: could not parse assets for their id's, error: Error: TypeError: Cannot read property 'length' of null
            at _getAssetId (/app/source/lib/cluster/storage/assets.js:90:28)
            at bound (domain.js:287:14)
            at runBound (domain.js:300:12)
            at tryCatcher (/app/source/node_modules/bluebird/js/main/util.js:26:23)
            at MappingPromiseArray._promiseFulfilled (/app/source/node_modules/bluebird/js/main/map.js:56:38)
            at MappingPromiseArray.init (/app/source/node_modules/bluebird/js/main/promise_array.js:92:18)
            at MappingPromiseArray.init (/app/source/node_modules/bluebird/js/main/map.js:29:23)
            at Async._drainQueue (/app/source/node_modules/bluebird/js/main/async.js:128:12)
            at Async._drainQueues (/app/source/node_modules/bluebird/js/main/async.js:133:10)
            at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/main/async.js:15:14)
            at processImmediate [as _immediateCallback] (timers.js:396:17) occurred on node: cluster_master

```

**Comment by kstaken** [comment]
All the other tests pass so just assets failed.

**Comment by kstaken** [comment]
Running `make clean` then `make test` allows all integration tests to pass. It's likely the prior issue was related to previous test runs on node:4. Going ahead with the merge.

**Pull request merged**
