### PR TITLE
API and client improvements and fixes

### LINKED ISSUE #644: Slicer count missing from /txt/jobs output
Now that the job is not expanded with the defaults from this: https://github.com/terascope/teraslice/pull/642 it doesn't contain `slicers` which is apparent from the output of the `/txt/jobs` api endpoint.  The example below shows a new job and then an old job:

```
job_id                                name     lifecycle   slicers  workers  _created                  _updated
------------------------------------  -------  ----------  -------  -------  ------------------------  ------------------------
7b7cc4e4-6240-426a-8996-992c4dc14226  foo      persistent           30       2018-01-10T23:46:16.836Z  2018-01-10T23:46:16.836Z
e6045322-0ec6-47c0-a599-7d9253ffe222  bar      persistent  1        30       2018-01-09T20:57:50.622Z  2018-01-10T22:05:49.853Z
```

The way this works is that `jobs` is passed into a utility called `makeTable` to generate the table here:

https://github.com/terascope/teraslice/blob/v0.28.0/lib/cluster/services/api.js#L423

I guess this can be resolve by merging `executionService` with `jobsService` prior to passing to `makeTable` or we could just remove the `slicers` column, which might be more appropriate since this value is already reported by `/txt/ex` where the information is actually stored.

### LINKED ISSUE #877: ex/errors endpoint
Add an `/ex/errors` endpoint to the api.  Currently the only way to get the errors for an ex_id is to hit the jobs endpoint,  i.e. `GET jobs/{job_id}/errors/{ex_id}`.  Functionality should be just like `/jobs/{job_id}/errors` or `/jobs/{job_id}/errors/{ex_id}`

### LINKED ISSUE #879: Fix Prometheus Endpoint Format
The metric rows should be in the the format: 
```
teraslice_slices_failed 8
```

Also, it would be helpful to have a `cluster` tag on the metrics to help differentiate clusters without relabel configs. 

```
# TYPE teraslice_slices_processed counter
teraslice_slices_processed{cluster="myCluster"} 15178
# TYPE teraslice_slices_failed counter
teraslice_slices_failed{cluster="myCluster"} 8
# TYPE teraslice_slices_queued counter
teraslice_slices_queued{cluster="myCluster"} 73
# TYPE teraslice_workers_joined counter
teraslice_workers_joined{cluster="myCluster"} 73
# TYPE teraslice_workers_disconnected counter
teraslice_workers_disconnected{cluster="myCluster"} 0
# TYPE teraslice_workers_reconnected counter
teraslice_workers_reconnected{cluster="myCluster"} 0
```

### LINKED ISSUE #880: Fix Jobs.list in teraslice-client-js and remove jobs method
`Jobs.list` shouldn't return executions:

https://github.com/terascope/teraslice/blob/v0.43.0/packages/teraslice-client-js/lib/jobs.js#L30-L33

and the `jobs()` method should be removed:

https://github.com/terascope/teraslice/blob/v0.43.0/packages/teraslice-client-js/lib/jobs.js#L35-L38

Earl should be updated to use `.list()` after this is fixed and we should look to see if we're using `Jobs.list()` and see if we're really expecting exes somewhere.

### LINKED ISSUE #884: Add support for filtering executions by multiple statuses
A feature was requested by Zach to filter jobs by more than one status in the teraslice client. This will require a change to `GET /ex?status=failed` to handle more than one, a simple fix would be to change the endpoint to support a comma-separated list of statuses, `status=initializing,running`.

### PR DESCRIPTION
**Pull request by peterdemartini**
- Add cluster to prometheus labels in /cluster/stats
- Add the ability to filter executions by multiple statuses
- Add the ability to get all execution errors to API and errors
- Fix issue jobs vs list issue in teraslice-client-js
- Update API docs
- Make API endpoints consistent
- Changed default search limit from 10000 to 100.
- Update a few dependencies

Resolves #879
Resolves #884
Resolves #880
Resolves #877
Resolves #644

### CODE REVIEW

**Comment by peterdemartini** [comment]
I am removing WIP, I think it is ready to go, but it should be reviewed by testing locally

**Comment by kstaken** [comment]
Is the N/A here intentional?

```
curl  localhost:5678/txt/controllers
name            job_id                                workers_available  workers_active  failed  queued  processed
--------------  ------------------------------------  -----------------  --------------  ------  ------  ---------
Data Generator  7ab049eb-0a0f-42ff-be5c-cf979c2b0f5c  1                  N/A             N/A     1       57
```

**Comment by peterdemartini** [comment]
@kstaken yes, and no, instead of having a blank value, we put 'N/A' to indicate that this value doesn't exist since applying default values. But your example should show zeros, I will fix that

**Comment by godber** [comment]
@kstaken since you have it up and running can you share the output of

```
curl -Ss -H "Accept: blah application/openmetrics-text; blah" localhost:5678/cluster/stats
```

here?

**Comment by kstaken** [comment]
Stopping on `ex` seemed to work but using `jobs` does this and does not stop.

```
curl -XPOST localhost:5678/jobs/c9fbc8ec-8d21-4f03-936d-53e72c18b505/_stop
{
    "status": "terminated"
}
```

**Comment by kstaken** [comment]
That is reporting correct however the job_id I was using was retrieve using `/txt/jobs?size=1` which gave me an old job. Appears the default sorting has been lost.

**Comment by kstaken** [comment]
Using the correct job_id stop works fine but `/txt/jobs` should give you newest jobs first.

**Pull request merged**
