### PR TITLE
Issue 794 worker deployment improvements

### PR DESCRIPTION
**Pull request by godber**
This PR includes the following improvements:

* #785 - add jobName and clusterName labels
* #782 - add support for volumes, by adding the following to a job definition

```
    "volumes": [
        {"name": "teraslice-data1", "path": "/data"}
    ],
```

* #793 - add support for resource requests and limits, by adding the following to a job definition

```
    "resources": {
        "minimum": {"cpu": 1, "memory": 2147483648},
        "limit": {"cpu": 2, "memory": 4294967296}
    },
```

* #794 - add support for affinity, by adding the following to a job definition

```
    "node_labels": [
        {"key": "zone", "value": "west"}
    ],
```

### CODE REVIEW

**Comment by godber** [comment]
I'll update the docs with the new options ... oh, there is probably a job schema I have to update too ...

**Comment by godber** [comment]
Changed to WIP, it's just occurred to me that I've only tweaked deployment but that won't apply to the execution_controller job.  Thats annoying.

**Comment by godber** [comment]
So, thinking about the execution controller job ... 

* it probably doesn't need volumes
* if it needs resource limits, it probably needs it's own rather than the same as the workers, perhaps I should hardcode a request and ignore limit for now
* affinity it probably needs

**Comment by kstaken** [comment]
Execution controller will absolutely need volumes.

**Comment by godber** [comment]
Well, if it needs two of the three, maybe I should just apply the same resource requirements and just run the execution controller Job object through the same code and call it good.

**Comment by kstaken** [comment]
Yeah to start it's probably fine to just share the same resource requirements.

**Comment by godber** [comment]
Ok, I've manually confirmed that the volume, resource and label restrictions have their basic functionality.  I'll add some details in the k8s readme about the new job options.  I also should probably track down the job schema validation stuff and update that.

**Comment by godber** [comment]
I have added my new schema components but not added tests for them.

**Comment by godber** [comment]
So close ... my resources validation function is not behaving how I expected ..

```
Job submission failed, error: Error validating job: Error: Validation failed for jobConfig: example-data-generator-job-resource - Cannot read property 'minimum' of undefined
```

labels and volumes worked though.

**Comment by godber** [comment]
This is all sorted out now.  The WIP tag is attached only as long as it takes us to finish discussing the proper naming of things.

The readme here has a summary of how the newly added job options are presented to users:

https://github.com/terascope/teraslice/blob/58b59cb6bd40a75e4c532d7a3c1dd4e3c2f19911/docs/k8s-clustering.md#teraslice-job-properties


Outstanding questions:

* The use of `resources.minimum` seems inappropriate (given that it actually gets used as a limit to some degree (weird design choice on their part).  Perhaps `resources.request` is fine even though that's what k8s uses.
* Kimbro was supposed to sleep on `node_labels` which is what I had chosen, these are intended to set affinity ... to be selectors ... `node_labels` was my choice, but maybe `node_selector` is good.  I am too wishy washy on this one.

**Pull request merged**
