### PR TITLE
slicer can not direct slices to a particular worker resolves #624

### LINKED ISSUE #624: allow slices to be sent to specific workers
We need the capabilities to allow the slicer to determine where a particular slice goes to. We need to be able to enforce that a slice of a particular type only head to a given worker. After the worker completes a slice it would need to respond back with enough meta data to empower this.

### PR DESCRIPTION
**Pull request by jsnoble**
this needs to be paired with the pr in the queue package.

In order to send a slice to a specific worker you will need to add a key to the slice from the reader-slicer

example slice from elasticsearch date slicer
```   
{
    start: someStartDate,
    end: someEndDate,
    count: data.count,
    request_worker: '172.29.0.170__4'  // the actual workerId
}
```

events to listen to:

'slice:invalid' => returns the slice, itmeans the slice was not able to be allocated in the worker queue, the state slice will be marked as invalid and you will need to change request_worker to another worker

'worker:ready' => returns workerId, use this to determine what workers have connected and their actual id

'network:disconnect' => returns a workerId, tells you what worker has dropped a connection to the slicer

'slice:success' => slice, the slice has been reported back by the worker and was sucessfull

slice:failure' => slice, the slice failed

### CODE REVIEW

**Comment by godber** [comment]
You mean this PR: https://github.com/terascope/queue/pull/5 right?

**Comment by erik-stephens** [comment]
When a new slicer is created, how should it enumerate the current workers?

**Comment by erik-stephens** [comment]
After chatting with @jsnoble, listening for `worker:ready` is the way to go, even on new slicer.  I understand the process to be:

1. job submitted
1. new slicer created
1. cluster master allocates workers to the job, emitting said event
1. new slicer waits until requested allocation filled or times out

Open questions:

1. How long should a slicer should wait?
1. If slicer times out waiting for full allocation, what is expected behavior?  Fail hard?  Move on as best it can?  Support either route via job configuration?

**Comment by kstaken** [comment]
Should we just close this PR?

**Comment by jsnoble** [comment]
another pr will have this feature

**Pull request closed without merging**
