### PR TITLE
release: (minor) teraslice@0.82.0

### PR DESCRIPTION
**Pull request by godber**

### CODE REVIEW

**Comment by godber** [comment]
refs #3270

**Comment by godber** [comment]
Ok, yeah, that was silly of me, we can't just do node 16 since we don't make node 16 assets:

`Could not find a release for terascope/elasticsearch-assets (linux x64)`

So I will dial this back to the latest node14.  Then we can ask the node16 question later.  The branch name will be a misnomer though.

**Comment by godber** [comment]
If this passes tests, we need to validate that the kafka asset still works with this build since I've removed it from the base image.

**Comment by godber** [comment]
This passed again after putting the kafka check back

https://app.travis-ci.com/github/terascope/teraslice/builds/260932765

**Review by jsnoble — APPROVED** [review]

**Pull request merged**
