### PR TITLE
Transforms graph array changes

### PR DESCRIPTION
**Pull request by jsnoble**
TODO:
- [x] need to migrate tag => tags
- [x] allow non unique tag chaining
- [x] create graph of all operations
- [x] check for cycles and throw errors
- [x] validation everything before being passed to op phases
- [x] create interface for each phase for what it requires
- [x] more robust implicit source and target field detection
- [x] additional tests
- [x] allow operations to implicitly pick up source fields from tags
- [x] allow join to use implicit fields
- [x] array creation operation
- [x] refactor loading configs from parsing and validation for greater composability
- [x] allow old post_processors that do not use tag/follow but selectors
- [x] documentation changes
- [x] allow ops to specify if they can take multi-inputs

### CODE REVIEW

**Comment by kstaken** [comment]
Can I get a summary of the breaking changes to the rules syntax?

**Comment by kstaken** [comment]
It looks like the `array` operation breaks if there's only one rule tagged.

```
{  "source_field": "input", "start": "Value=", "end": "EOP", "target_field": "value", "tag": "value", "output": false }

{ "follow": "value", "post_process": "array", "target_field": "myarray" }
```

```
Error: could not instantiate phase manager: Error: Join configuration is misconfigured, could not determine fields to join {"follow":"value","post_process":"array","target_field":"myarray","__id":"j6M1BwNc5f","source_fields":["value"]}
    at MakeArray.validateConfig (/snapshot/teraslice/packages/ts-transforms/dist/src/operations/lib/transforms/array.js:25:19)
    at new OperationBase (/snapshot/teraslice/packages/ts-transforms/dist/src/operations/lib/base.js:9:14)
    at new TransformOpBase (/snapshot/teraslice/packages/ts-transforms/dist/src/operations/lib/transforms/base.js:10:9)
    at new MakeArray (/snapshot/teraslice/packages/ts-transforms/dist/src/operations/lib/transforms/array.js:10:9)
    at loadOp (/snapshot/teraslice/packages/ts-transforms/dist/src/phases/post_process_phase.js:14:20)
    at Array.map (<anonymous>)
    at base_1.default.constructor.lodash_1.default.forOwn (/snapshot/teraslice/packages/ts-transforms/dist/src/phases/post_process_phase.js:17:45)
    at isBind (/snapshot/teraslice/node_modules/lodash/lodash.js:4911:15)
    at baseForOwn (/snapshot/teraslice/node_modules/lodash/lodash.js:2996:24)
    at Function.forOwn (/snapshot/teraslice/node_modules/lodash/lodash.js:13015:24)
    at PhaseManager.init (/snapshot/teraslice/packages/ts-transforms/dist/src/phases/phase_manager.js:37:19)
    at <anonymous>
```

**Comment by jsnoble** [comment]
Fixed the array issue. As for the rules listed above:
```
{  "source_field": "input", "start": "Value=", "end": "EOP", "target_field": "value", "tag": "value", "output": false }

{ "follow": "value", "post_process": "array", "target_field": "myarray" }
```
This allows for the creation of an array in the post_process phase which would allow for additional chaining afterwords. The multivalue setting makes an array at the end of output phase which is against the flexibility that we need. So it would seem that we should remove that.

As for rules changes:
- You can specify a config with both `tag:value` and `tags: ['value', value2']`
- tags are non unique per configurations
- it use to allow specifing a a join rules as follows 
```
{ selector: hello:world, source_field: first, target_field: first_name}
{ selector: hello:world, source_field: first, target_field: first_name}
```

**Comment by kstaken** [comment]
I think you're right that `multivalue` no longer serves a good purpose. The processing is much cleaner and more logical using `array`. Let's drop `multivalue`.

**Comment by jsnoble** [comment]
To show more about multivalue:
```
// Rules
{ "selector": "other:value", "source_field": "first", "target_field": "field", "multivalue": true }
{ "selector": "other:value", "source_field": "second", "target_field": "field", "multivalue": true }

// Incoming Data
[
  { other: 'value', first: 'hello', second: 'world' }
]

//Results
[ 
  { field: ['hello', 'world']}
]
```

vs being explicit and using the array creation operation
```
// Rules
{ "selector": "other:value", "source_field": "first", "target_field": "field1", "tag": "makeArray", "output": false }
{ "selector": "other:value", "source_field": "second", "target_field": "field2", "tag": "makeArray", "output": false }
{ "follow": "makeArray", "post_process": "array", "target_field"}

// Incoming Data
[
  { other: 'value', first: 'hello', second: 'world' }
]

//Results
[ 
  { field: ['hello', 'world']}
]
```
The pros of this is that it will allow additional post_processing and validation after array creation. The downside is that you need to make sure to add the array post_process config, and put output:false on the first extractions for it to behave the same

**Comment by kstaken** [comment]
Setting a rule to `follow` with no corresponding tag results in this error.

```
Error: could not instantiate phase manager: Error: could not validate rules error: TypeError: Cannot read property 'forEach' of undefined
    at lodash_1.default.forOwn.ids.forEach (/snapshot/teraslice/packages/ts-transforms/dist/src/loader/utils.js:138:26)
    at Array.forEach (<anonymous>)
    at lodash_1.default.forOwn (/snapshot/teraslice/packages/ts-transforms/dist/src/loader/utils.js:136:13)
    at isBind (/snapshot/teraslice/node_modules/lodash/lodash.js:4911:15)
    at baseForOwn (/snapshot/teraslice/node_modules/lodash/lodash.js:2996:24)
    at Function.forOwn (/snapshot/teraslice/node_modules/lodash/lodash.js:13015:24)
    at Object.parseConfig (/snapshot/teraslice/packages/ts-transforms/dist/src/loader/utils.js:135:22)
    at RulesValidator.validate (/snapshot/teraslice/packages/ts-transforms/dist/src/loader/rules-validator.js:11:33)
    at Loader.load (/snapshot/teraslice/packages/ts-transforms/dist/src/loader/loader.js:34:33)
    at <anonymous>
    at Loader.load (/snapshot/teraslice/packages/ts-transforms/dist/src/loader/loader.js:37:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at PhaseManager.init (/snapshot/teraslice/packages/ts-transforms/dist/src/phases/phase_manager.js:37:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Pull request merged**
