### PR TITLE
Asset tests

### PR DESCRIPTION
**Pull request by godber**
This commit includes the following:

* Test for adding and deleting an asset
* Error returned when uploading an asset without asset.json
* Job runs and right number of workers join with type1 asset
* Job runs and right number of workers join with type2 asset
* Example assets type1, type2 and bad

It's worth noting that I've modified the asset teraslice worker
and master asset directories to be stored inside the containers
so that they are not accidentally shared on the host.

I also had to increase the number of iterations waited for the workers joined.
Hopefully this is sufficient.  These tests add about 40s to the total runtime on
my mac.

### CODE REVIEW

**Comment by godber** [comment]
I could DRY up the two good asset tests I suppose.

**Comment by godber** [comment]
@jsnoble I checked and confirmed that the PR on the client has been merged and I cleared up my state and re-ran test to ensure that I didn't have anything unexpected in my `node_modules` directories.

**Comment by godber** [comment]
The test currently waits for the job to get to Running and then waits for the requested number of workers to be joined ... like this:

```
                    .then((job) => {
                        job.waitForStatus('running');
                        return job;
                    })
                    .then(job => wait.forWorkersJoined(job.id(), workers, 20))
```

Unfortunately, I think this can result in the test hanging because the job completes prior to satisfying the workersJoined condition.

@jsnoble, wouldn't it be sufficient to wait for the job `completed` state?

**Comment by jsnoble** [comment]
tests pass for me:

teraslice

    api endpoint
      ✓ should update job specs (15 secs)

    worker allocation
      ✓ should cycle through after state changes with other jobs running (23 secs)

    id reader
      ✓ should support reindexing (23 secs)
      ✓ should support reindexing by hex id (13 secs)
      ✓ should support reindexing by hex id + key_range (11 secs)
      ✓ should complete after stopping and restarting (27 secs)

    elasticsearch bulk
      ✓ should support multisend (7 secs)

    reindex
      ✓ should work for simple case (5 secs)
      ✓ should work when no data is returned with lucene query (5 secs)
      ✓ should collect cluster level stats (0.011 sec)
      ✓ should complete after lifecycle changes (14 secs)
      ✓ should support idempotency (31 secs)

    worker allocation
      ✓ with 1 worker (6 secs)
      ✓ with 5 workers (13 secs)
      ✓ with 13 out of requested 20 workers (22 secs)

    cluster state
      ✓ should match default configuration (0.007 sec)
      ✓ should update after adding and removing a worker node (6 secs)
      ✓ should update after adding and removing 20 worker nodes (28 secs)
      ✓ should be correct for running job with 1 worker (6 secs)
      ✓ should be correct for running job with 3 workers (8 secs)

    job validation
      ✓ should be rejected with empty index selector index name (0.019 sec)
      ✓ should be rejected with empty reader index name (0.03 sec)
      ✓ should be rejected with slicers = 0 (0.007 sec)
      ✓ should be rejected with slicers < 0 (0.009 sec)
      ✓ should be rejected with negative workers == 0 (0.015 sec)
      ✓ should be rejected with invalid lifecycle (0.027 sec)
      ✓ should be rejected if empty (0.094 sec)

    Asset Tests

      After uploading an asset
        ✓ can be deleted (0.24 sec)

      Uploading a bad asset
        ✓ returns an error (0.041 sec)

      After starting a job with a Type 1 asset
        ✓ should eventually have all workers active (18 secs)

      After starting a job with a Type 2 asset
        ✓ should eventually have all workers active (24 secs)

**************************************************
*                    Pending                     *
**************************************************

1) teraslice worker allocation should scale from 13 to 20 workers
  Temporarily disabled with xit

Executed 31 of 32 specs INCOMPLETE (1 PENDING) in 6 mins 49 secs.

**Comment by jsnoble** [comment]
@godber yes you are right, so all you need to do is change it to a persistent job for all the tests and you should be good. Once you make that change i will pull it in

**Comment by godber** [comment]
Ok, I have changed this to a persistent job and plugged my leaky promises, integration tests pass:

```
make test
./docker-compose.sh # do every time in case variables or linked modules change
$(npm bin)/jasmine
Jasmine started
 - Bringing Docker environment up
 - Waiting for Elasticsearch... Ready
 - Waiting for Teraslice... Ready
 - Cleaning up teraslice state & prior test results
 - Making sure example data generated
Global setup complete. Starting tests...

  teraslice

    api endpoint
      ✓ should update job specs (17 secs)

    worker allocation
      ✓ should cycle through after state changes with other jobs running (30 secs)

    id reader
      ✓ should support reindexing (38 secs)
      ✓ should support reindexing by hex id (15 secs)
      ✓ should support reindexing by hex id + key_range (13 secs)
      ✓ should complete after stopping and restarting (48 secs)

    elasticsearch bulk
      ✓ should support multisend (13 secs)

    reindex
      ✓ should work for simple case (6 secs)
      ✓ should work when no data is returned with lucene query (5 secs)
      ✓ should collect cluster level stats (0.007 sec)
      ✓ should complete after lifecycle changes (30 secs)
      ✓ should support idempotency (37 secs)

    worker allocation
      ✓ with 1 worker (9 secs)
      ✓ with 5 workers (26 secs)
      ✓ with 13 out of requested 20 workers (41 secs)

    cluster state
      ✓ should match default configuration (0.008 sec)
      ✓ should update after adding and removing a worker node (7 secs)
      ✓ should update after adding and removing 20 worker nodes (34 secs)
      ✓ should be correct for running job with 1 worker (10 secs)
      ✓ should be correct for running job with 3 workers (11 secs)

    job validation
      ✓ should be rejected with empty index selector index name (0.024 sec)
      ✓ should be rejected with empty reader index name (0.016 sec)
      ✓ should be rejected with slicers = 0 (0.011 sec)
      ✓ should be rejected with slicers < 0 (0.014 sec)
      ✓ should be rejected with negative workers == 0 (0.01 sec)
      ✓ should be rejected with invalid lifecycle (0.009 sec)
      ✓ should be rejected if empty (0.006 sec)

    Asset Tests

      After uploading an asset
        ✓ can be deleted (0.137 sec)

      Uploading a bad asset
        ✓ returns an error (0.05 sec)

      After starting a job with a Type 1 asset specified by ID
        ✓ should eventually have all workers joined (30 secs)

      After starting a job with a Type 2 asset specified by ID
        ✓ should eventually have all workers joined (27 secs)

**************************************************
*                    Pending                     *
**************************************************

1) teraslice worker allocation should scale from 13 to 20 workers
  Temporarily disabled with xit

Executed 31 of 32 specs INCOMPLETE (1 PENDING) in 7 mins 33 secs.
```

I am going to remove the WIP on this and give you the option of merging while I go back to enhancing this in two ways:

* handling updated assets
* validating assets on worker filesystem

**Comment by jsnoble** [comment]
i ran the tests as well and they pass

**Pull request merged**
