### PR TITLE
v0.65.2 - Asset loading improvements

### PR DESCRIPTION
**Pull request by godber**
I don't know that this actually resolves the socket errors reported in #1931, but it might.

- Set the timeout on the api server and proxy request from the cluster master to the api server
- Reduce the number of file system writes needs to load an asset
- Simplify the asset loading process by not trying to magically move the asset directory up a directory when it is not built correctly.
- Improves error handling when saving assets

### CODE REVIEW

**Comment by godber** [comment]
The tests fail and doing my typical manual test of loading an asset and running a job fails as well, I get the following message in the logs when loading an asset (note the `undefinied`):

```
[2020-05-21T20:44:05.341Z] DEBUG: teraslice/14 on teraslice-master-57b6b9b44d-8pptt: loading an asset (assignment=assets_service, module=assets_service, worker_id=-i99OlOP)
[2020-05-21T20:44:18.911Z]  INFO: teraslice/14 on teraslice-master-57b6b9b44d-8pptt: assets: undefined, id: 99c659972729d8e2ba9771363f3d1bbd1fa72887 has been saved to assets_directory and elasticsearch (assignment=assets_service, module=assets_storage, worker_id=-i99OlOP)
```

**Comment by godber** [comment]
@peterdemartini can you clearly state the assumption the code is making about the structure of assets.

**Comment by peterdemartini** [comment]
> @peterdemartini can you clearly state the assumption the code is making about the structure of assets.

The directory structure required is:

```txt
├── asset.json
├── example/
│   ├── processor.ts
│   └── schema.ts
└── nested_example/
    └── example_2/
        ├── processor.ts
        └── schema.ts
```

**Comment by godber** [comment]
Oh, could you bump the version and then approve and build.

**Pull request merged**
