### PR TITLE
Asset bundle deployment and API

### PR DESCRIPTION
**Pull request by jsnoble**
example curl
  curl -XPOST -H "Content-Type: application/octet-stream" localhost:5678/assets --data-binary @zipFile.zip 

- [x] Need to add more api to deal with assets dir
- [x] Need to add more error handling
- [x] add meta data attributes

### CODE REVIEW

**Comment by godber** [comment]
refs: #335

**Comment by kstaken** [comment]
Where does this store the assets after they're uploaded?

**Comment by kstaken** [comment]
Ahh looks like it defaults to `lib/assets`. And the PR includes `lib/assets/test_dir` which I'm guessing isn't intended. This should probably default to a folder in the root of the project rather than under `lib`.

**Comment by kstaken** [comment]
This is storing stuff on the file system under the name of the file. The name is supposed to just be metadata and there can be many assets with the same name. It should be using the id for the name of the directory and all internal functionality should be tied to that id. That will allow multiple versions of the same asset to exist on the nodes at the same time which is critical.

**Comment by kstaken** [comment]
Adding to my prior comment, my thinking on this is that when a job specifies a list of assets those would be made available to the job as module loadable paths which would then have the ops under them. 

This implies that the zip file would contain the `op` as a directory inside of it which would allow a single asset to contain many `ops`.

```
my_asset1/
    op_module1/
    op_module2/
    op_module3/
```

Which is then zipped up as `my_asset.zip` and when deployed would look like this.

```
asset_directory/
    ASSET_ID/
       op_module1/
       op_module2/
       op_module3/
```

Then you could also have

```
asset_directory/
    ASSET_ID/
        my_simple_module.js
```

or

```
asset_directory/
    ASSET_ID/
         my_lookup_data.csv
```

or even 

```
asset_directory/
    ASSET_ID/
         my_simple_module.js
         my_lookup_data.csv
         op_module1/
```

And this also implies we're going to need an API to access these files from the job which is whole new can of worms.

**Comment by kstaken** [comment]
Seems I'm unable to get a job to run that references assets. I tried it via ID and name. Nothing appears to get downloaded.

```
{"name":"teraslice","hostname":"kteramac.local","pid":96662,"module":"jobs_service","level":30,"msg":"Scheduling job: d9bb3424-85a7-414e-b430-bb8af85c08cc","time":"2017-05-05T01:31:35.289Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96661,"level":30,"msg":"Starting 1 slicer","time":"2017-05-05T01:31:35.317Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96661,"module":"node_master","level":30,"msg":"node kteramac.local is checking assets for job d9bb3424-85a7-414e-b430-bb8af85c08cc","time":"2017-05-05T01:31:35.319Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96661,"level":30,"msg":"Starting 1 assets","time":"2017-05-05T01:31:35.319Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96661,"module":"node_master","level":30,"msg":"Attempting to allocate 1 workers.","time":"2017-05-05T01:31:35.368Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96661,"level":30,"msg":"Starting 1 worker","time":"2017-05-05T01:31:35.368Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96667,"ex_id":"d9bb3424-85a7-414e-b430-bb8af85c08cc","module":"worker","worker_id":"10.0.1.8__5","level":30,"msg":"worker 10.0.1.8__5 is online, communicating with host: http://10.0.1.8:45679","time":"2017-05-05T01:31:36.091Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":96661,"level":30,"msg":"assets has exited, id: 4, code: 0, signal: null","time":"2017-05-05T01:31:36.096Z","v":0}
```

**Comment by kstaken** [comment]
This message is amusing. Apparently there might be an Error.

```
{"name":"teraslice","hostname":"kteramac.local","pid":16712,"module":"jobs_service","level":50,"msg":"could not submit job Error validating job: Error: Error loading module: test-module , error: an error occurred while attempting to load the code","time":"2017-05-09T21:53:18.593Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":16712,"module":"api_service","level":50,"msg":"Could not submit job, error: Error validating job: Error: Error loading module: test-module , error: an error occurred while attempting to load the code","time":"2017-05-09T21:53:18.593Z","v":0}
```

**Comment by kstaken** [comment]
If all the code is removed out of the assets directory on the master node then your jobs throw errors and a new copy of the code isn't downloaded. I understand the code is required in order to validate the job however the assumption that the code can be kept on that node forever is problematic. Isn't it possible to look at the job and get the list of assets that should be downloaded?

**Comment by kstaken** [comment]
Is you submit a job with an invalid asset reference you get the following message.

```
{
    "error": 500,
    "message": "Job submission failed: Error validating job: Error: Could not retrieve code for: test-module , error message: Error: Cannot find module 'test-module'"
}
```

While that message is technically correct it might help the user better understand what's going on if the invalid asset reference is flagged as an issue instead.

**Comment by kstaken** [comment]
I changed that hardcoded IP to `127.0.0.1` and then get this error.
```
Error downloading assets Error: ENOENT: no such file or directory, mkdir '/Users/kstaken/projects/opensource/teraslice/assets/eefad2721c7656d7de8e53b26f489906254333c6'
        at Error (native)
[2017-05-19T23:12:45.283Z] ERROR: teraslice/86844 on kteramac.local: Error in worker: 2 pid: 86844
[2017-05-19T23:12:45.284Z] ERROR: teraslice/86844 on kteramac.local:
    Error: ENOENT: no such file or directory, mkdir '/Users/kstaken/projects/opensource/teraslice/assets/eefad2721c7656d7de8e53b26f489906254333c6'
        at Error (native)
```

**Comment by kstaken** [comment]
Submitting a job results in no workers. Has the test suite been run on this?

```
ex_id                                 workers_available  workers_active  failed  queued  processed  subslice_by_key
------------------------------------  -----------------  --------------  ------  ------  ---------  ---------------
63ce4bf8-b859-4413-9510-ca07361ffbcc  0                  0               0       20      0          0
```

**Comment by kstaken** [comment]
If there is an issue with the assets bundle the error sequence isn't very graceful. 

Here I had an extra comma in assets.json. This crashed the worker and caused a cascade of secondary errors.

```
[2017-05-23T17:50:02.492Z] ERROR: teraslice/98385 on kteramac.local: (module=assets_storage)
    Error downloading assets SyntaxError: /Users/kstaken/projects/opensource/teraslice/assets/3f8fba5625c804cc615b4bfd4cd70b06bcc09b7d/asset.json: Unexpected token }
        at Object.parse (native)
        at Object.Module._extensions..json (module.js:424:27)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at /Users/kstaken/projects/opensource/teraslice/lib/utils/file_utils.js:50:39
        at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:510:31)
        at Promise._settlePromiseAt (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:584:18)
        at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:128:12)
        at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:396:17)
[2017-05-23T17:50:02.497Z] ERROR: teraslice/98385 on kteramac.local: Error in worker: 2 pid: 98385
[2017-05-23T17:50:02.497Z] ERROR: teraslice/98385 on kteramac.local:
    SyntaxError: /Users/kstaken/projects/opensource/teraslice/assets/3f8fba5625c804cc615b4bfd4cd70b06bcc09b7d/asset.json: Unexpected token }
        at Object.parse (native)
        at Object.Module._extensions..json (module.js:424:27)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at /Users/kstaken/projects/opensource/teraslice/lib/utils/file_utils.js:50:39
        at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:510:31)
        at Promise._settlePromiseAt (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:584:18)
        at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:128:12)
        at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:396:17)
[2017-05-23T17:50:02.498Z] ERROR: teraslice/98385 on kteramac.local:
    Error: SyntaxError: /Users/kstaken/projects/opensource/teraslice/assets/3f8fba5625c804cc615b4bfd4cd70b06bcc09b7d/asset.json: Unexpected token }
        at Object.parse (native)
        at Object.Module._extensions..json (module.js:424:27)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at /Users/kstaken/projects/opensource/teraslice/lib/utils/file_utils.js:50:39
        at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:510:31)
        at Promise._settlePromiseAt (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:584:18)
        at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:128:12)
        at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:396:17)
        at Object.ensureErrorObject (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:261:20)
        at Promise._rejectCallback (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:472:22)
        at /Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:489:17
        at /Users/kstaken/projects/opensource/teraslice/lib/utils/file_utils.js:63:25
        at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:510:31)
        at Promise._settlePromiseAt (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:584:18)
        at Promise._settlePromises (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:700:14)
        at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:396:17)
[2017-05-23T17:50:03.110Z] ERROR: teraslice/98384 on kteramac.local: Error in worker: 1 pid: 98384
[2017-05-23T17:50:03.110Z] ERROR: teraslice/98384 on kteramac.local: socket hang up
[2017-05-23T17:50:03.111Z] ERROR: teraslice/98384 on kteramac.local:
    Error: socket hang up
        at createHangUpError (_http_client.js:213:15)
        at Socket.socketOnEnd (_http_client.js:305:23)
        at emitNone (events.js:72:20)
        at Socket.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:923:12)
        at nextTickCallbackWith2Args (node.js:458:9)
        at process._tickDomainCallback (node.js:413:17)
```

**Comment by kstaken** [comment]
Modules aren't extracting correctly.

My test module has the following structure which I've confirmed is captured in the .zip

```
/
    asset.json
    test-module/
         index.js
```

When I deploy it the upload succeeds but the assets directory only has asset.json in it.

```
# ls 6ce6634b9d460df1d77b3f7a1dd1be6d6a23ba61/
asset.json
```

And then jobs fail.

```
curl -XPOST localhost:5678/jobs -d@job.json
{
    "error": 500,
    "message": "Job submission failed: Error validating job: Error: Could not retrieve code for: test-module , error message: Error: Cannot find module 'test-module'"
}
```

**Comment by kstaken** [comment]
Due to some ambiguity over the structure of the zip files we're going to make asset.json required and it will be used as the guide to interpreting how the zip file is structured and handled. The issue is related to whether the zip does or does not have a contained directory at the root.

If asset.json is at the root of the .zip it will just be extracted with no manipulation.
```
/
   asset.json
   my_module/
        index.js
```

However if the .zip contains a top level directory.

```
/
    my_asset/
         asset.json
         my_module/
              index.js
```

Then the location of asset.json will be used to determine the "real" root of the asset bundle and it will be unzipped as if that directory doesn't exist.

```
/
   asset.json
   my_module/
        index.js
```

**Comment by kstaken** [comment]
Jobs are running!!!! But this error could be better and not sure where 
\n is coming from. 

Maybe `No asset with the provided name and version could be located.` 

```
{
    "error": 500,
    "message": "Job submission failed: error while attempting to load asset: my-test-module:0.0.2, either \n                            the asset does not exist or the version is incorrect"
}
```

**Comment by kstaken** [comment]
Let's also add an optional `description` field to asset.json and store it in ES as an analyzed text field.

**Comment by kstaken** [comment]
There is some trickyness here related to versions. An asset can be uploaded multiple times with the same version but with different content and therefore a different ID. This gets added to the index multiple times and it's unclear what code you get when you run a job.

I think there are a couple ways this could be addressed
1. Make version +  name + id immutable. So that once a version has been uploaded uploading the same version again with different content becomes an error.
    * This is the way npm handles this but it can kind of be a pain if it's something you don't really care about the version of.
2. Simply sort by _created and use the newest record.
    * This has the downside of polluting the namespace and makes version kind of a weak idea.

**Comment by kstaken** [comment]
Assets txt API doesn't seem to work.

```
curl localhost:5678/txt/assets
{"error":500,"message":"Cannot read property 'slice' of undefined"}
```

**Comment by kstaken** [comment]
This error message could be tweaked. Maybe: "asset name:my-test-module2 with version:0.0.1 already exists, please increment the version and send again"

```
{"error":"asset name:my-test-module2 and version:0.0.1 is already exists, please change the version of this asset bundle and send again"}
```

**Comment by kstaken** [comment]
I think we're good to merge this. Additional issues will log as separate tickets.

**Comment by kstaken** [comment]
This required some updates to the integration tests but those are now passing ... merging.

**Pull request merged**
