### PR TITLE
DataFrame Improvements

### PR DESCRIPTION
**Pull request by peterdemartini**
- [x] Add more transformation and validations for columns
- [x] Add benchmarks
- [x] Improve performance by only storing unique values
- [x] Improve AggregregationFrame to DataFrame API

Continuation from https://github.com/terascope/teraslice/pull/2182

### CODE REVIEW

**Comment by peterdemartini** [comment]
Performance benchmarks:

BEFORE:

```txt
filterBy                                1278.59 op/s ±  1.21%   (80 samples)
concat 1000 records        11.95 op/s ± 30.95%     (17 samples)
sum a column.                   4146.26 op/s ±  1.86%   (81 samples)
toUpperCase transform    3349.57 op/s ±  0.88%   (79 samples)
toLowerCase transform    4623.92 op/s ±  0.65%   (81 samples)
increment transform         5412.17 op/s ±  0.89%   (81 samples)
decrement transform        5467.77 op/s ±  0.56%   (80 samples)
```

AFTER

```txt
filterBy                               339.09 op/s ±  3.16%     (74 samples)
concat 1000 records        17.41 op/s ± 28.45%      (23 samples)
sum a column                   144891.67 op/s ±  2.41%  (77 samples)
toUpperCase transform   3810.11 op/s ±  5.03%    (71 samples)
toLowerCase transform   5866.08 op/s ±  2.48%    (77 samples)
increment transform        28681.30 op/s ±  2.16%   (75 samples)
decrement transform       29772.45 op/s ±  1.80%   (77 samples)
```

**Comment by kstaken** [comment]
This is definitely loading data much faster.

**Comment by peterdemartini** [comment]
I added a ticket for tracking the migration of transformation and validators: https://github.com/terascope/teraslice/issues/2242

**Review by kstaken — APPROVED** [review]
This looks good

**Pull request merged**
