### PR TITLE
Issue#465 expose config api

### PR DESCRIPTION
**Pull request by godber**
Adding `/cluster/config` API endpoint that exposes `context.sysconfig`.

This PR contains a second commit that just updates style things.

refs #465

### CODE REVIEW

**Comment by godber** [comment]
Accessing the new API endpoint like this

```bash
curl -Ss localhost:5678/cluster/config
```

returns this:

```json
{
    "terafoundation": {
        "environment": "development",
        "log_path": "/Users/godber/Workspace/terascope/opensource/teraslice",
        "logging": [
            "console"
        ],
        "log_level": "info",
        "log_buffer_limit": 30,
        "log_buffer_interval": 60000,
        "workers": 4,
        "connectors": {
            "elasticsearch": {
                "default": {
                    "host": [
                        "127.0.0.1:9200"
                    ],
                    "sniffOnStart": false,
                    "sniffOnConnectionFault": false,
                    "requestTimeout": 120000,
                    "deadTimeout": 30000,
                    "maxRetries": 3,
                    "__reused": true,
                    "log": {
                        "_events": {},
                        "_eventsCount": 3
                    },
                    "hosts": [
                        "127.0.0.1:9200"
                    ],
                    "keepAlive": true,
                    "minSockets": 10,
                    "maxSockets": 11
                }
            }
        }
    },
    "teraslice": {
        "ops_directory": "/app/source/examples/ops/",
        "assets_directory": "/Users/godber/Workspace/terascope/opensource/teraslice/assets",
        "shutdown_timeout": 60000,
        "reporter": "",
        "hostname": "10.167.0.1",
        "workers": 4,
        "master": true,
        "master_hostname": "127.0.0.1",
        "port": 5678,
        "name": "teracluster",
        "state": {
            "connection": "default"
        },
        "timeout": 300000,
        "slicer_timeout": 180000,
        "slicer_queue_length": 10000,
        "slicer_port_range": "45679:46678",
        "moderator": false,
        "moderator_limit": 0.85,
        "moderator_resume": 0.5,
        "moderator_interval": 10000
    },
    "_nodeName": "stretch.local.1"
```

**Comment by godber** [comment]
This particular implementation could be risky if it is possible for the connection definitions to contain authentication information.

**Comment by erik-stephens** [comment]
That risk was my only concern with this.  I suspect there will be a relatively small subset of the config that will warrant being exposed, so I vote for having the endpoint explicitly define what parts of the config are exposed.

**Comment by kstaken** [comment]
Yeah this seems both very helpful and highly problematic at the same time. It's definitely possible for connectors to define auth info. 

It's also only exposing the config for the master node and the config on the workers could be different.

Obviously if you think about the requirements for a future GUI it's going to be useful to have access to almost all of this information. 

So I guess I have no answers.

**Comment by godber** [comment]
We need to think this through more.

**Pull request closed without merging**
