### PR TITLE
Breaking changes to `elasticsearch-api->buldSend` to fix retry support

### PR DESCRIPTION
**Pull request by peterdemartini**
Makes breaking changes to the elasticsearch api `bulkSend` method so that the retries work correctly.

### CODE REVIEW

**Review by jsnoble — APPROVED** [review]
LGTM, though is there any reason why this could not be added directly to bulkSend? why does it have to be another method?

**Comment by peterdemartini** [comment]
> LGTM, though is there any reason why this could not be added directly to bulkSend? why does it have to be another method?

I actually we could do that it mean we would have to do major update on that package

**Review by ciorg — APPROVED** [review]
LGTM

**Comment by jsnoble** [comment]
> > LGTM, though is there any reason why this could not be added directly to bulkSend? why does it have to be another method?
> 
> Actually we could do that it mean we would have to do major update on that package

I would prefer that, better to have a well behaved method then a good one and a one that does not retry. It would simply things. I don't know if this needs a major as nothing is broken nor has the interface changed. It has an additional feature to retry, but it behaves exactly how it did before on a regular query

**Comment by peterdemartini** [comment]
> > > LGTM, though is there any reason why this could not be added directly to bulkSend? why does it have to be another method?
> > 
> > 
> > Actually we could do that it mean we would have to do major update on that package
> 
> I would prefer that, better to have a well behaved method then a good one and a one that does not retry. It would simply things. I don't know if this needs a major as nothing is broken nor has the interface changed. It has an additional feature to retry, but it behaves exactly how it did before on a regular query

I am not sure if you read the code right because this is very much a breaking change. The input now takes `{ action: Metadata, data?: Record<string, unknown> }[]` vs the raw flat bulk request functions and the return value returns a number instead of that last success retry response.

**Pull request merged**
